### ISSUE TITLE
Weird Crash (Issue)

### ISSUE THREAD

**Issue by InsaanNotFound** [Draylar/variant#2]
Happens not instantly, but when using Variants with conjunction of Distant Horizons mod (newest CF available version). Cause is unknown but it might be related to minecart entity. Game instantly crashes.

_[20:24:55] [Server thread/WARN]: UUID of added entity already exists: class_1694['Minecart with Chest'/2506, l='ServerLevel[New World]', x=478.50, y=-48.50, z=248.50]
[20:24:56] [Server thread/WARN]: UUID of added entity already exists: class_1694['Minecart with Chest'/2508, l='ServerLevel[New World]', x=477.50, y=-43.50, z=162.50]
[20:24:56] [Render thread/INFO]: [CHAT] You have 6 trophies to [claim] !_

Followed by:

_[20:25:31] [Server thread/ERROR]: Exception stopping the server
[20:25:31] [Render thread/INFO]: Stopping worker threads
[20:25:31] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:166) ~[?:?]
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1563) ~[?:?]
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1311) ~[?:?]
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1034) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:813) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_583.method_2816(net.minecraft.class_1297, float, float, float)" because "entityModel" is null
	**at dev.draylar.variant.client.VariantOverlayFeatureRenderer.render(VariantOverlayFeatureRenderer.java:57) ~[variant-1.1.0-1.18.2.jar:?]**
	at net.minecraft.client.render.entity.LivingEntityRenderer.render(LivingEntityRenderer:145) ~[?:?]
	at net.minecraft.client.render.entity.MobEntityRenderer.render(MobEntityRenderer:45) ~[?:?]
	at net.minecraft.client.render.entity.MobEntityRenderer.render(MobEntityRenderer:18) ~[?:?]
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:135) ~[?:?]
	... 22 more
[20:25:31] [Render thread/ERROR]: GL ERROR 0x500 from API: GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.
[20:25:31] [Render thread/ERROR]: Unhandled game exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_5667()" because the return value of "fabric.com.seibel.lod.common.wrappers.minecraft.MinecraftClientWrapper.getPlayer()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at fabric.com.seibel.lod.common.wrappers.minecraft.MinecraftClientWrapper.sendChatMessage(MinecraftClientWrapper.java:368) ~[DistantHorizons-1.6.3a-1.18.2.jar:?]
	at com.seibel.lod.core.api.ClientApi.logToChat(ClientApi.java:136) ~[DistantHorizons-1.6.3a-1.18.2.jar:?]
	at com.seibel.lod.core.logging.ConfigBasedLogger.log(ConfigBasedLogger.java:73) ~[DistantHorizons-1.6.3a-1.18.2.jar:?]
	at com.seibel.lod.core.logging.ConfigBasedLogger.error(ConfigBasedLogger.java:78) ~[DistantHorizons-1.6.3a-1.18.2.jar:?]
	at com.seibel.lod.core.render.GLProxy.logMessage(GLProxy.java:137) ~[DistantHorizons-1.6.3a-1.18.2.jar:?]
	at com.seibel.lod.core.util.GLMessageOutputStream.flush(GLMessageOutputStream.java:53) ~[DistantHorizons-1.6.3a-1.18.2.jar:?]
	at java.io.PrintStream.write(PrintStream.java:570) ~[?:?]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234) ~[?:?]
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313) ~[?:?]
	at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:111) ~[?:?]
	at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:178) ~[?:?]
	at java.io.PrintStream.write(PrintStream.java:699) ~[?:?]
	at java.io.PrintStream.print(PrintStream.java:863) ~[?:?]
	at java.io.PrintStream.append(PrintStream.java:1303) ~[?:?]
	at java.io.PrintStream.append(PrintStream.java:63) ~[?:?]
	at java.util.Formatter$FormatSpecifier.appendJustified(Formatter.java:3093) ~[?:?]
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:3083) ~[?:?]
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:3056) ~[?:?]
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2933) ~[?:?]
	at java.util.Formatter.format(Formatter.java:2689) ~[?:?]
	at java.io.PrintStream.format(PrintStream.java:1209) ~[?:?]
	at java.io.PrintStream.printf(PrintStream.java:1105) ~[?:?]
	at org.lwjgl.opengl.GLUtil.printDetail(GLUtil.java:111) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GLUtil.lambda$setupDebugMessageCallback$1(GLUtil.java:69) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL11C.glPolygonMode(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL11.glPolygonMode(GL11.java:5040) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at com.mojang.blaze3d.platform.GlStateManager._polygonMode(GlStateManager:478) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.polygonMode(RenderSystem:391) ~[client-intermediary.jar:?]
	at fudge.notenoughcrashes.utils.GlUtil.resetState(GlUtil.java:52) ~[notenoughcrashes-4.1.4+1.18.2-fabric.jar:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.resetStates(InGameCatcher.java:41) ~[notenoughcrashes-4.1.4+1.18.2-fabric.jar:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:32) ~[notenoughcrashes-4.1.4+1.18.2-fabric.jar:?]
	at net.minecraft.client.MinecraftClient.modify$dpl000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:20510) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:759) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]_

**Comment by Sunconure11** [comment]
Encountering the same issue.

https://gist.github.com/Sunconure11/882204de0c740b14c12b073441d09245

@Draylar
